(source gnu)
(source melpa)

(depends-on "bind-key")
(depends-on "cask")
(depends-on "dash")
(depends-on "diminish")
(depends-on "drag-stuff")
(depends-on "epl")
(depends-on "exec-path-from-shell")
(depends-on "expand-region")
(depends-on "f")
(depends-on "flycheck")
(depends-on "flycheck-cask")
(depends-on "git-commit-mode")
(depends-on "git-rebase-mode")
(depends-on "htmlize")
(depends-on "idle-highlight-mode")
(depends-on "let-alist")
(depends-on "magit")
(depends-on "multiple-cursors")
(depends-on "nyan-mode")
(depends-on "package-build")
(depends-on "pallet")
(depends-on "pkg-info")
(depends-on "popwin")
(depends-on "prodigy")
(depends-on "projectile")
(depends-on "s")
(depends-on "shut-up")
(depends-on "smartparens")
(depends-on "smex")
(depends-on "iedit")
(depends-on "use-package")
(depends-on "web-mode")

(depends-on "auto-complete")
(depends-on "yasnippet")

(depends-on "evil")
(depends-on "evil-surround")
(depends-on "evil-leader")
(depends-on "evil-numbers")
(depends-on "evil-matchit")
(depends-on "evil-exchange")
(depends-on "evil-easymotion")
(depends-on "evil-escape")
(depends-on "evil-iedit-state")
(depends-on "evil-smartparens")

(depends-on "ido")
(depends-on "flx-ido")
(depends-on "ido-ubiquitous")
(depends-on "ido-at-point")
(depends-on "ido-vertical-mode")
(depends-on "ido-sort-mtime")
(depends-on "ido-hacks")
(depends-on "ido-select-window")

(depends-on "workgroups2")
(depends-on "frame-restore")

(depends-on "sublime-themes")
(depends-on "powerline")
(depends-on "powerline-evil")
(depends-on "fill-column-indicator")
(depends-on "git-gutter+")
(depends-on "git-gutter-fringe+")
